### ISSUE TITLE
name for route not best practice?

### ISSUE THREAD

**Issue by KlimovCode** [alexeymezenin/laravel-realworld-example-app#1]

**Comment by alexeymezenin** [comment]
@KlimovCode If you use the routes in your app, then sure, you should always name the routes. For example, if you use something like `return redirect()->route('some-named-route');` using named routes is a great idea.

But in this case, it's an API, so route names would just add noise.

**Comment by KlimovCode** [comment]
Oh, right! I just didn't read README.md :-)

Thanks for your work!
