### ISSUE TITLE
God method

### ISSUE THREAD

**Issue by notsmoke** [alexeymezenin/laravel-realworld-example-app#2]
https://github.com/alexeymezenin/laravel-realworld-example-app/blob/aa45dfbc71e60a0b137a284f02ac90f288b3c927/app/Models/Article.php#L44
подскажите это тот самый случай или другой?

[Single responsibility principle](https://github.com/alexeymezenin/laravel-best-practices/blob/master/russian.md#%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF-%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8-single-responsibility-principle)

**Comment by alexeymezenin** [comment]
Этот метод, несмотря на то, что он кажется большим, делает одну вещь - строит запрос в БД с заданными фильтрами. Дело в том, что [ТЗ на этот проект подразумевает](https://gothinkster.github.io/realworld/docs/specs/backend-specs/endpoints#list-articles), что пользователь API сможешь фильтровать данные сразу по нескольким критериям. Если бы у нас фильтры должны были работать отдельно (например, 4 разных эндпоинта под 4 разных фильтра), имело бы смысл разбить этот метод на несколько.

**Comment by notsmoke** [comment]
у нас 4 условия фильтрации, соответственно по любому из них мы идем править метод. 
+ [Не повторяйся](https://github.com/alexeymezenin/laravel-best-practices/blob/master/russian.md#%D0%BD%D0%B5-%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D1%8F%D0%B9%D1%81%D1%8F-dry)
+ читать его очень больно.

как реализовать 4 фильтра на одном эндпоинте можно постомтреть тут [laravel-query-builder](https://github.com/spatie/laravel-query-builder)

**Comment by alexeymezenin** [comment]
На счет DRY соглашусь, руки так и тянутся переиспользовать when. Такое бывает. Проблема в том, что при переиспользовании кода конкретно в этом случае, код будет менее читаемым и более громоздким. Это как раз тот довольно редкий случай, когда DRY не нужно использовать.

На счет пакета, это плохая практика использовать сторонний пакет для решения очень небольшой задачи. При использовании любого стороннего пакета всегда есть вероятность того, что он что-то сломает в приложении в будущем (лично сталкивался с этим десятки раз).

**Comment by notsmoke** [comment]
> На счет пакета, это плохая практика использовать сторонний пакет для решения очень небольшой задачи.

кто сказал? я вам не предлагал его юзать, а лишь посмотреть как можно красиво реализовать конкретно вашу задачу

> При использовании любого стороннего пакета всегда есть вероятность того, что он что-то сломает в приложении в будущем (лично сталкивался с этим десятки раз).

вы в папку вендер ларавеля смотрели?

> Это как раз тот довольно редкий случай, когда DRY не нужно использовать.

)) как скажите, удачи вам!

**Comment by alexeymezenin** [comment]
Покажи пожалуйста как бы ты сделал эту фичу. Видимо я тебя не до конца понимаю.

Единственное, что смог сделать - это использовать local scope. Озвученной тобой проблемы это не решает, но, по крайней мере, код переиспользуется. Хотя, выглядит ненамного чище.

**Comment by notsmoke** [comment]
> Покажи пожалуйста как бы ты сделал эту фичу. Видимо я тебя не до конца понимаю.
> 
> Единственное, что смог сделать - это использовать local scope. Озвученной тобой проблемы это не решает, но, по крайней мере, код переиспользуется. Выглядит пусть ненамного, но чище.

отправил pr

**Comment by alexeymezenin** [comment]
Спасибо, что показал свою имплементацию.

Ну вот смотри, вместо шести читаемых строчек кода - [три строки сам local scope](https://github.com/alexeymezenin/laravel-realworld-example-app/blob/main/app/Models/Article.php#L58) и [три строки его использование](https://github.com/alexeymezenin/laravel-realworld-example-app/blob/main/app/Models/Article.php#L46), ты создаешь несколько классов с дополнительными десятками строк кода (тест не считаю), при этом используется велик, вместо встроенных инструментов фреймворка.

Я не понимаю как это лучше.

**Comment by notsmoke** [comment]
> Я не понимаю как это лучше [твоего PR](https://github.com/alexeymezenin/laravel-realworld-example-app/pull/3/commits/a10c8dea6f9d2c3e2fd69d96383f0f94e4b530f7).
здесь я ни чем не могу помочь))

> Ну вот смотри, вместо шести читаемых строчек кода

на вскидку:
- добавьте еще 7 условий фильтрации
- переиспользуйте свою реализацию в другой модели (и даже не в одной, как будет в реальной жизни)
- дайте порефать этот код своему другу
- 
нет! это не велик!))

> ты создаешь **несколько дополнительных классов с дополнительными десятками строк кода**
> это плохая практика использовать сторонний пакет для решения очень небольшой задачи

вы заложник каких то ошибочных практик

на этом извините я ухожу! было приятно пообщаться! приятного вам кодинга!

**Comment by MT-cod** [comment]
Предлагается заняться оверинжинрингом :)
