### ISSUE TITLE
Метод filter() в модели Article

### ISSUE THREAD

**Issue by c0ntr-all** [alexeymezenin/laravel-realworld-example-app#4]
Как работает метод filter() вот в этом участке кода и откуда он берется?
_Файл: App\Models\Article.php_
```
public function getFiltered(array $filters): Collection
{
    return $this->filter($filters, 'tag', 'tags', 'name')
        ->filter($filters, 'author', 'user', 'username')
        ->filter($filters, 'favorited', 'users', 'username')
        ->when(array_key_exists('offset', $filters), function ($q) use ($filters) {
            $q->offset($filters['offset'])->limit($filters['limit']);
        })
        ->with('user', 'users', 'tags', 'user.followers')
        ->get();
}
```
В моделях (query builder) нет такого метода. Он есть в коллекциях, но там только callback в качестве параметра и вообще не имеет отношения к данной ситуации. Да и я вообще по всему laravel ничего похожего не нашел. Уже голову сломал!

**Comment by alexeymezenin** [comment]
Это [local scope](https://laravel.com/docs/8.x/eloquent#local-scopes), сам метод [здесь](https://github.com/alexeymezenin/laravel-realworld-example-app/blob/7f152e298134866d39fb3a3d714f7c3b3d3c4984/app/Models/Article.php#L56).

**Comment by c0ntr-all** [comment]
Понял. Спасибо!
